### ISSUE TITLE
TODO pile before making a release

### ISSUE THREAD

**Issue by tschoonj** [tschoonj/xraylib-rust#8]
- [ ] xraylib crate: add missing functions (and their tests)
- [ ] xraylib crate: add docstrings to functions, constants, structs
- [ ] xraylib crate: avoid reimporting everything from xraylib-sys
- [ ] all crates: add README.md
- [ ] xraylib-src: update submodule to latest xraylib release
- [ ] figure out how to publish crates
